### PR TITLE
Change railties dependency to allow for Rails 5

### PR DESCRIPTION
**Pull request by jasonivers**

### CODE REVIEW

**Comment by zedtux** [comment]
Thank you so much @jasonivers. Unfortunately there are conflicts. Can you please fix them?

**Comment by jasonivers** [comment]
Yes, but it will have to wait until tomorrow.

**Comment by zedtux** [comment]
Alright, thank you @jasonivers

**Comment by zedtux** [comment]
Actually the gemspec is specifying the version lower than Rails 6 so this PR is not need. I'm so sorry @jasonivers for having asked without double checking.

**Pull request closed without merging**
